export const getAlphabet = () => {
    let data =
    { A:
   [ { name: 'Afghanistan', code: '+93', region: 'AF'},
     { name: 'Albania', code: '+355', region: 'AL'},
     { name: 'Algeria', code: '+213', region: 'DZ'},
     { name: 'American Samoa', code: '+1684', region: 'AS'},
     { name: 'Andorra', code: '+376', region: 'AD'},
     { name: 'Angola', code: '+244', region: 'AO'},
     { name: 'Anguilla', code: '+1264', region: 'AI'},
     { name: 'Antarctica', code: '+672', region: 'AQ'},
     { name: 'Antigua and Barbuda', code: '+1268', region: 'AG'},
     { name: 'Argentina', code: '+54', region: 'AR'},
     { name: 'Armenia', code: '+374', region: 'AM'},
     { name: 'Aruba', code: '+297', region: 'AW'},
     { name: 'Australia', code: '+61', region: 'AU'},
     { name: 'Austria', code: '+43', region: 'AT'},
     { name: 'Azerbaijan', code: '+994', region: 'AZ'} ],
  B:
   [ { name: 'Bahamas', code: '+1242', region: 'BS'},
     { name: 'Bahrain', code: '+973', region: 'BH'},
     { name: 'Bangladesh', code: '+880', region: 'BD'},
     { name: 'Barbados', code: '+1246', region: 'BB'},
     { name: 'Belarus', code: '+375', region: 'BY'},
     { name: 'Belgium', code: '+32', region: 'BE'},
     { name: 'Belize', code: '+501', region: 'BZ'},
     { name: 'Benin', code: '+229', region: 'BJ'},
     { name: 'Bermuda', code: '+1441', region: 'BM'},
     { name: 'Bhutan', code: '+975', region: 'BT'},
     { name: 'Bolivia, Plurinational State of', code: '+591', region: 'BO'},
     { name: 'Bosnia and Herzegovina', code: '+387', region: 'BA'},
     { name: 'Botswana', code: '+267', region: 'BW'},
     { name: 'Brazil', code: '+55', region: 'BR'},
     { name: 'British Indian Ocean Territory', code: '+246', region: 'IO'},
     { name: 'Brunei Darussalam', code: '+673', region: 'BN'},
     { name: 'Bulgaria', code: '+359', region: 'BG'},
     { name: 'Burkina Faso', code: '+226', region: 'BF'},
     { name: 'Burundi', code: '+257', region: 'BI'} ],
  C:
   [ { name: 'Cambodia', code: '+855', region: 'KH'},
     { name: 'Cameroon', code: '+237', region: 'CM'},
     { name: 'Canada', code: '+1', region: 'CA'},
     { name: 'Cape Verde', code: '+238', region: 'CV'},
     { name: 'Cayman Islands', code: '+ 345', region: 'KY'},
     { name: 'Central African Republic', code: '+236', region: 'CF'},
     { name: 'Chad', code: '+235', region: 'TD'},
     { name: 'Chile', code: '+56', region: 'CL'},
     { name: 'China', code: '+86', region:'CN'},
     { name: 'Christmas Island', code: '+61', region: 'CX'},
     { name: 'Cocos (Keeling) Islands', code: '+61', region: 'CC'},
     { name: 'Colombia', code: '+57', region: 'CO'},
     { name: 'Comoros', code: '+269', region: 'KM'},
     { name: 'Congo', code: '+242', region: 'CG'},
     { name: 'Congo, The Democratic Republic of the Congo', code: '+243', region: 'CD'},
     { name: 'Cook Islands', code: '+682', region: 'CK'},
     { name: 'Costa Rica', code: '+506', region: 'CR'},
     { name: 'Cote d\'Ivoire', code: '+225', region: 'CI'},
     { name: 'Croatia', code: '+385', region: 'HR'},
     { name: 'Cuba', code: '+53', region: 'CU'},
     { name: 'Cyprus', code: '+357', region: 'CY'},
     { name: 'Czech Republic', code: '+420', region: 'CZ'} ],
  D:
   [ { name: 'Denmark', code: '+45', region: 'DK'},
     { name: 'Djibouti', code: '+253', region: 'DJ'},
     { name: 'Dominica', code: '+1767', region: 'DM'},
     { name: 'Dominican Republic', code: '+1849', region: 'DO'} ],
  E:
   [ { name: 'Ecuador', code: '+593', region: 'EC'},
     { name: 'Egypt', code: '+20', region: 'EG'},
     { name: 'El Salvador', code: '+503', region: 'SV'},
     { name: 'Equatorial Guinea', code: '+240', region: 'GQ'},
     { name: 'Eritrea', code: '+291', region: 'ER'},
     { name: 'Estonia', code: '+372', region: 'EE'},
     { name: 'Ethiopia', code: '+251', region: 'ET'} ],
  F:
   [ { name: 'Falkland Islands (Malvinas)', code: '+500', region: 'FK'},
     { name: 'Faroe Islands', code: '+298', region: 'FO'},
     { name: 'Fiji', code: '+679', region: 'FJ'},
     { name: 'Finland', code: '+358', region: 'FI'},
     { name: 'France', code: '+33', region: 'FR'},
     { name: 'French Guiana', code: '+594', region: 'GF'},
     { name: 'French Polynesia', code: '+689', region: 'PF'} ],
  G:
   [ { name: 'Gabon', code: '+241', region: 'GA'},
     { name: 'Gambia', code: '+220', region: 'GM'},
     { name: 'Georgia', code: '+995', region: 'GE'},
     { name: 'Germany', code: '+49', region: 'DE'},
     { name: 'Ghana', code: '+233', region: 'GH'},
     { name: 'Gibraltar', code: '+350', region: 'GI'},
     { name: 'Greece', code: '+30', region: 'GR'},
     { name: 'Greenland', code: '+299', region: 'GL'},
     { name: 'Grenada', code: '+1473', region: 'GD'},
     { name: 'Guadeloupe', code: '+590', region: 'GP'},
     { name: 'Guam', code: '+1671', region: 'GU'},
     { name: 'Guatemala', code: '+502', region: 'GT'},
     { name: 'Guernsey', code: '+44', region: 'GG'},
     { name: 'Guinea', code: '+224', region: 'GN'},
     { name: 'Guinea-Bissau', code: '+245', region: 'GW'},
     { name: 'Guyana', code: '+595', region: 'GY'} ],
  H:
   [ { name: 'Haiti', code: '+509', region: 'HT'},
     { name: 'Holy See (Vatican City State)', code: '+379', region: 'VA'},
     { name: 'Honduras', code: '+504', region: 'HN'},
     { name: 'Hong Kong', code: '+852', region: 'HK'},
     { name: 'Hungary', code: '+36', region: 'HU'} ],
  I:
   [ { name: 'Iceland', code: '+354', region: 'IS'},
     { name: 'India', code: '+91', region: 'IN'},
     { name: 'Indonesia', code: '+62', region: 'ID'},
     { name: 'Iran, Islamic Republic of Persian Gulf', code: '+98', region:'IR'},
     { name: 'Iraq', code: '+964', region: 'IQ'},
     { name: 'Ireland', code: '+353', region: 'IE'},
     { name: 'Isle of Man', code: '+44', region: 'IM'},
     { name: 'Israel', code: '+972', region:'IL'},
     { name: 'Italy', code: '+39', region: 'IT'} ],
  J:
   [ { name: 'Jamaica', code: '+1876', region: 'JM'},
     { name: 'Japan', code: '+81', region: 'JP'},
     { name: 'Jersey', code: '+44', region: 'JE'},
     { name: 'Jordan', code: '+962', region: 'JO'} ],
  K:
   [ { name: 'Kazakhstan', code: '+77', region: 'KZ'},
     { name: 'Kenya', code: '+254', region: 'KE'},
     { name: 'Kiribati', code: '+686', region: 'KI'},
     { name: 'North Korea', code: '+850', region: 'KP'},
     { name: 'South Korea', code: '+82', region: 'KR'},
     { name: 'Kuwait', code: '+965', region: 'KW'},
     { name: 'Kyrgyzstan', code: '+996', region: 'KG'} ],
  L:
   [ { name: 'Laos', code: '+856', region: 'LA'},
     { name: 'Latvia', code: '+371', region: 'LV'},
     { name: 'Lebanon', code: '+961', region: 'LB'},
     { name: 'Lesotho', code: '+266', region: 'LS'},
     { name: 'Liberia', code: '+231', region: 'LR'},
     { name: 'Libya', code: '+218', region: 'LY'},
     { name: 'Liechtenstein', code: '+423', region: 'LI'},
     { name: 'Lithuania', code: '+370', region: 'LT'},
     { name: 'Luxembourg', code: '+352', region: 'LU'} ],
  M:
   [ { name: 'Macao', code: '+853', region: 'MO'},
     { name: 'Macedonia', code: '+389', region: 'MK'},
     { name: 'Madagascar', code: '+261', region: 'MG'},
     { name: 'Malawi', code: '+265', region: 'MW'},
     { name: 'Malaysia', code: '+60', region: 'MY'},
     { name: 'Maldives', code: '+960', region: 'MV'},
     { name: 'Mali', code: '+223', region: 'ML'},
     { name: 'Malta', code: '+356', region: 'MT'},
     { name: 'Marshall Islands', code: '+692', region: 'MH'},
     { name: 'Martinique', code: '+596', region: 'MQ'},
     { name: 'Mauritania', code: '+222', region: 'MR'},
     { name: 'Mauritius', code: '+230', region: 'MU'},
     { name: 'Mayotte', code: '+262', region: 'YT'},
     { name: 'Mexico', code: '+52', region: 'MX'},
     { name: 'Micronesia, Federated States of Micronesia', code: '+691', region: 'FM'},
     { name: 'Moldova', code: '+373', region: 'MD'},
     { name: 'Monaco', code: '+377', region: 'MC'},
     { name: 'Mongolia', code: '+976', region: 'MN'},
     { name: 'Montenegro', code: '+382', region: 'ME'},
     { name: 'Montserrat', code: '+1664', region: 'MS'},
     { name: 'Morocco', code: '+212', region: 'MA'},
     { name: 'Mozambique', code: '+258', region: 'MZ'},
     { name: 'Myanmar', code: '+95', region: 'MM'} ],
  N:
   [ { name: 'Namibia', code: '+264', region: 'NA'},
     { name: 'Nauru', code: '+674', region: 'NR'},
     { name: 'Nepal', code: '+977', region: 'NP'},
     { name: 'Netherlands', code: '+31', region: 'NL'},
     { name: 'Netherlands Antilles', code: '+599', region: 'ANN'},
     { name: 'New Caledonia', code: '+687', region: 'NC'},
     { name: 'New Zealand', code: '+64', region: 'NZ'},
     { name: 'Nicaragua', code: '+505', region: 'NI'},
     { name: 'Niger', code: '+227', region: 'NE'},
     { name: 'Nigeria', code: '+234', region: 'NG'},
     { name: 'Niue', code: '+683', region: 'NU'},
     { name: 'Norfolk Island', code: '+672', region: 'NF'},
     { name: 'Northern Mariana Islands', code: '+1670', region: 'MP'},
     { name: 'Norway', code: '+47', region: 'NO'} ],
  O: [ { name: 'Oman', code: '+968', region: 'OM'} ],
  P:
   [ { name: 'Pakistan', code: '+92', region: 'PK'},
     { name: 'Palau', code: '+680', region: 'PW'},
     { name: 'Palestinian Territory', code: '+970', region: 'PS'},
     { name: 'Panama', code: '+507', region: 'PA'},
     { name: 'Papua New Guinea', code: '+675', region: 'PG'},
     { name: 'Paraguay', code: '+595', region: 'PY'},
     { name: 'Peru', code: '+51', region: 'PE'},
     { name: 'Philippines', code: '+63', region: 'PH'},
     { name: 'Pitcairn', code: '+872', region: 'PN'},
     { name: 'Poland', code: '+48', region: 'PL'},
     { name: 'Portugal', code: '+351', region: 'PT'},
     { name: 'Puerto Rico', code: '+1939', region: 'PR'} ],
  Q: [ { name: 'Qatar', code: '+974', region: 'QA'} ],
  R:
   [ { name: 'Romania', code: '+40', region: 'RO'},
     { name: 'Russia', code: '+7', region: 'RU'},
     { name: 'Rwanda', code: '+250', region: 'RW'},
     { name: 'Reunion', code: '+262', region: 'RE'} ],
  S:
   [ { name: 'Saint Barthelemy', code: '+590', region: 'BL'},
     { name: 'Saint Helena, Ascension and Tristan Da Cunha', code: '+290', region: 'SH'},
     { name: 'Saint Kitts and Nevis', code: '+1869', region: 'KN'},
     { name: 'Saint Lucia', code: '+1758', region: 'LC'},
     { name: 'Saint Martin', code: '+590', region: 'MF'},
     { name: 'Saint Pierre and Miquelon', code: '+508', region: 'PM'},
     { name: 'Saint Vincent and the Grenadines', code: '+1784', region: 'VC'},
     { name: 'Samoa', code: '+685', region: 'WS'},
     { name: 'San Marino', code: '+378', region: 'SM'},
     { name: 'Sao Tome and Principe', code: '+239', region: 'ST'},
     { name: 'Saudi Arabia', code: '+966', region: 'SA'},
     { name: 'Senegal', code: '+221', region: 'SN'},
     { name: 'Serbia', code: '+381', region: 'RS'},
     { name: 'Seychelles', code: '+248', region: 'SC'},
     { name: 'Sierra Leone', code: '+232', region: 'SL'},
     { name: 'Singapore', code: '+65', region: 'SG'},
     { name: 'Slovakia', code: '+421', region: 'SK'},
     { name: 'Slovenia', code: '+386', region: 'SI'},
     { name: 'Solomon Islands', code: '+677', region: 'SB'},
     { name: 'Somalia', code: '+252', region: 'SO'},
     { name: 'South Africa', code: '+27', region: 'ZA'},
     { name: 'South Sudan', code: '+211', region: 'SS'},
     { name: 'South Georgia and the South Sandwich Islands', code: '+500', region: 'GS'},
     { name: 'Spain', code: '+34', region: 'ES'},
     { name: 'Sri Lanka', code: '+94', region: 'LK'},
     { name: 'Sudan', code: '+249', region: 'SD'},
     { name: 'Suriname', code: '+597', region: 'SR'},
     { name: 'Svalbard and Jan Mayen', code: '+47', region: 'SJ'},
     { name: 'Swaziland', code: '+268', region: 'SZ'},
     { name: 'Sweden', code: '+46', region: 'SE'},
     { name: 'Switzerland', code: '+41', region: 'CH'},
     { name: 'Syria', code: '+963', region: 'SY'} ],
  T:
   [ { name: 'Taiwan', code: '+886', region: 'TW'},
     { name: 'Tajikistan', code: '+992', region: 'TJ'},
     { name: 'Tanzania, United Republic of Tanzania', code: '+255', region: 'TZ'},
     { name: 'Thailand', code: '+66', region: 'TH'},
     { name: 'Timor-Leste', code: '+670', region: 'TL'},
     { name: 'Togo', code: '+228', region: 'TG'},
     { name: 'Tokelau', code: '+690', region: 'TK'},
     { name: 'Tonga', code: '+676', region: 'TO'},
     { name: 'Trinidad and Tobago', code: '+1868', region: 'TT'},
     { name: 'Tunisia', code: '+216', region: 'TN'},
     { name: 'Turkey', code: '+90', region: 'TR'},
     { name: 'Turkmenistan', code: '+993', region: 'TM'},
     { name: 'Turks and Caicos Islands', code: '+1649', region: 'TC'},
     { name: 'Tuvalu', code: '+688', region: 'TV'} ],
  U:
   [ { name: 'Uganda', code: '+256', region: 'UG'},
     { name: 'Ukraine', code: '+380', region: 'UA'},
     { name: 'United Arab Emirates', code: '+971', region:'AE'},
     { name: 'United Kingdom', code: '+44', region: 'GB'},
     { name: 'United States', code: '+1', region: 'US'},
     { name: 'Uruguay', code: '+598', region: 'UY'},
     { name: 'Uzbekistan', code: '+998', region: 'UZ'} ],
  V:
   [ { name: 'Vanuatu', code: '+678', region: 'VU'},
     { name: 'Venezuela', code: '+58', region: 'VE'},
     { name: 'Vietnam', code: '+84', region: 'VN'},
     { name: 'Virgin Islands, British', code: '+1284', region: 'VG'},
     { name: 'Virgin Islands, U.S.', code: '+1340', region: 'VI'} ],
  W: [ { name: 'Wallis and Futuna', code: '+681', region: 'WF'} ],
  Y: [ { name: 'Yemen', code: '+967', region: 'YE'} ],
  Z:
   [ { name: 'Zambia', code: '+260', region: 'ZM'},
     { name: 'Zimbabwe', code: '+263', region: 'ZW'} ] }
  return data
}
